services:
  app:
    container_name: bussiness-perfomance-analysis-app
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./source:/app
    tty: true